table General_Details_table
	lineageTag: d723982e-881a-44a5-a386-932da7df8560

	column id
		dataType: int64
		formatString: 0
		lineageTag: 9ca61109-d2ba-4ba7-99a8-8e8d1378f60e
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 901ffcba-5598-44dd-85d1-55f94ab9cd1b
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		lineageTag: febb38f5-00af-4ae9-85fb-8b33ed51e027
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ever_married
		dataType: string
		lineageTag: ba2aaaaa-09b6-4821-90ef-58c78b3013d0
		summarizeBy: none
		sourceColumn: ever_married

		annotation SummarizationSetBy = Automatic

	column Residence_type
		dataType: string
		lineageTag: 23ba9e5a-d8d1-4ca4-a3c5-dccd7b420f82
		summarizeBy: none
		sourceColumn: Residence_type

		annotation SummarizationSetBy = Automatic

	column Worktype_cleaned
		dataType: string
		lineageTag: c9c06f02-18f5-4a64-aae5-21e6611796b4
		summarizeBy: none
		sourceColumn: Worktype_cleaned

		annotation SummarizationSetBy = Automatic

	column Age_related_risk =
			IF(General_Details_table[age]>55,
			"High Risk Age",
			"Low Risk Age")
		dataType: string
		lineageTag: 38e6a908-621f-4150-bb8b-88dc438e0505
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'High Risk Factor' =
			IF(General_Details_table[gender]="Male" &&
			RELATED(Risk_Factors_Table[heart_disease])=1,
			"High Risk 2",
			"Low Risk 2")
		dataType: string
		lineageTag: c5980e0f-9050-4036-a0e8-f81f33787430
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition General_Details_table = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\DVA_Power Bi Data\healthcare_dataset_stroke_data_v1.xlsx"), null, true),
				    General_Details_table_DefinedName = Source{[Item="General_Details_table",Kind="DefinedName"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(General_Details_table_DefinedName, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"gender", type text}, {"age", type number}, {"ever_married", type text}, {"work_type", type text}, {"Residence_type", type text}}),
				    Gender_null_NA = Table.ReplaceValue(#"Changed Type",null,"NA",Replacer.ReplaceValue,{"gender"}),
				    Replaced_Age_null_Avg = Table.ReplaceValue(Gender_null_NA,null,List.Average(#"Gender_null_NA"[age]),Replacer.ReplaceValue,{"age"}),
				    Replaced_evermarried_null_NA = Table.ReplaceValue(Replaced_Age_null_Avg,null,"NA",Replacer.ReplaceValue,{"ever_married"}),
				    #"Worktype Cleaning" = Table.AddColumn(Replaced_evermarried_null_NA, "Text After Delimiter", each Text.AfterDelimiter([work_type], "-"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Worktype Cleaning",{{"Text After Delimiter", "Worktype_cleaned"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"work_type"}),
				    Residence_Type_null_NA = Table.ReplaceValue(#"Removed Columns",null,"NA",Replacer.ReplaceValue,{"Residence_type"}),
				    #"Replaced_worktype_""""_NA" = Table.ReplaceValue(Residence_Type_null_NA,"","NA",Replacer.ReplaceValue,{"Worktype_cleaned"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced_worktype_""""_NA",{{"age", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

