table 'Measure Table'
	lineageTag: c815d906-7813-4a04-a7cd-8e0f75971fcd

	measure Average_age = AVERAGE(General_Details_table[age])
		lineageTag: e54fd821-4719-40b9-8bed-8e5db0a156f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Stroke_rate = SUM(Risk_Factors_Table[stroke])/COUNT(Risk_Factors_Table[stroke])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 18221dbc-d115-424f-b92a-03f8b3ffc7bc

	measure 'Total ID''s' = DISTINCTCOUNT(General_Details_table[id])
		formatString: 0
		lineageTag: 5bad8555-24d7-4b96-a38e-7d08410511ad

	measure 'All ID''s' =
			CALCULATE([Total ID's],
			ALL(General_Details_table))
		formatString: 0
		lineageTag: da86e299-6d58-49fb-86ee-490a0a174a51

	measure 'Percent of Total' = DIVIDE([Total ID's], COUNTROWS(ALL(General_Details_table)))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2ff74e5d-5f4f-46d0-b7d5-1b270be51d87

	measure Hypertension_Rate = DIVIDE(SUM(Risk_Factors_Table[hypertension]),COUNT(Risk_Factors_Table[hypertension]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c2f79eb0-bb6a-4648-b6ae-8668dd600d16

	measure Heart_Disease_Rate = DIVIDE(SUM(Risk_Factors_Table[heart_disease]),COUNT(Risk_Factors_Table[heart_disease]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5f37245e-4976-4447-b563-81d248791f90

	partition 'Measure Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

